### ISSUE TITLE
not installing

### ISSUE THREAD

**Issue by Jaliladjadie** [nix-community/nix-on-droid#424] opened 2024-11-14 21:32 UTC
trying to install apt and geting this error: "
<borked>
-bash-5.2$ nix-shell -p apt
warning: Nix search path entry '/data/data/com.termux.nix/files/home/.nix-defexpr/channels/nixpkgs/' does not exist, ignoring
error:
       … <borked>

         at «none»:0: (source not available)

       … while calling the 'import' builtin

         at «string»:1:18:

            1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (apt) ]; } ""
             |                  ^

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «none»:0: (source not available)
</borked>"

**Comment by t184256** [comment] 2024-11-14 22:50
Duplicate of https://github.com/nix-community/nix-on-droid/issues/409. If you installed with flakes, use flakes.

**Closed by t184256** 2024-11-14 22:50 UTC

**Comment by Pm081220** [comment] 2024-11-16 19:35
at «none»:0: (source not available)

   … while calling the 'import' builtin

     at «string»:1:18:

        1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (apt) ]; } ""
         |                  ^

   (stack trace truncated; use '--show-trace' to show the full trace)

   error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

   at «none»:0: (source not available)
