### ISSUE TITLE
Can I install desktop in nix on droid

### ISSUE THREAD

**Issue by Greenarrow4245** [nix-community/nix-on-droid#319] opened 2024-01-08 08:52 UTC

**Comment by Greenarrow4245** [comment] 2024-01-08 14:16
Hello

**Comment by DataEraserC** [comment] 2024-01-26 02:02
https://github.com/nix-community/nix-on-droid/issues/75

**Comment by t184256** [comment] 2024-06-03 05:52
Sounds like a duplicate of #75 indeed.

**Closed by t184256** 2024-06-03 05:52 UTC

**Comment by Greenarrow4245** [comment] 2024-06-03 05:54
forgot to close issue
